initial a3to9e

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: a1to5x
+name: a3to9e
 
 on:
   workflow_dispatch:
@@ -24,7 +24,7 @@ on:
          default: 'true'
 
 jobs:
-  a1to5x:
+  a3to9e:
     runs-on: ubuntu-18.04
     continue-on-error: false
 
@@ -51,140 +51,126 @@ jobs:
           ${{ github.event.inputs.mode }} ${{ github.event.inputs.filelink }} -${{ github.event.inputs.output }} "${filename}.zip"
           ls -al
 
-      - name: Payload Extracting
+      - name: Extracting Payload 
         run: |
           echo "Payload Extracting"
           unzip ${{ steps.var.outputs.filename }}.zip
           rm -rf ${{ steps.var.outputs.filename }}.zip
           python3 update-payload-extractor/extract.py payload.bin --output_dir ./output/
-          sudo ls -R output/
+          ls output/
 
-      - name: Fstab Patching
+      - name: Patching fstabs
         run: |
-            echo "system"
-            mkdir system/
-            sudo mount output/system.img system/
-            sudo cp system/system/build.prop ./
-            cat system/system/vendor/etc/fstab.qcom
-            fstab="system/system/vendor/etc/fstab.qcom"
+            echo "vendor"
+            mkdir vendor/
+            sudo mount output/vendor.img vendor/
+            cat vendor/etc/fstab.qcom
+            fstab="vendor/etc/fstab.qcom"
             sudo sed -i 's/,slotselect//g' $fstab
             sudo sed -i 's/,verify//g' $fstab
             sudo sed -i 's/,avb//g' $fstab
             sudo sed -i 's/forceencrypt/encryptable/g' $fstab
             sudo sed -i 's/fileencryption=ice/encryptable=footer/g' $fstab
-            sudo sed -i '/mnt_point/{n;/system/d;}' $fstab
-            sudo sed -i '/mnt_point/a\/dev/block/bootdevice/by-name/system		/system			ext4	ro								wait,recoveryonly' $fstab
-            sudo sed -i '/mnt_point/G' $fstab
-            sudo sed -i '/mnt_point/a\/dev/block/bootdevice/by-name/recovery		/recovery		emmc	defaults							defaults' $fstab
-            sudo sed -i '/mnt_point/a\\n/dev/block/bootdevice/by-name/boot		/boot			emmc	defaults							defaults' $fstab
-            sudo sed -i '/persist/i\/dev/block/bootdevice/by-name/cache		/cache			f2fs	nosuid,nodev,noatime,inline_xattr,flush_merge,data_flush	wait,formattable,check' $fstab
-            sudo sed -i '/cache/a\\n/dev/block/bootdevice/by-name/cache		/cache			ext4	nosuid,nodev,noatime						wait,formattable,check' $fstab
-            cat system/system/vendor/etc/fstab.qcom
-            sudo cp system/system/vendor/etc/fstab.qcom output/fstab.qcom
-            sudo umount system
-            sudo rm -rf system
+            sudo sed -i '/mnt_point/a\/dev/block/bootdevice/by-name/cache                     /cache                   ext4    nosuid,noatime,nodev,barrier=1                       wait' $fstab
+            cat vendor/etc/fstab.qcom
+            sudo cp vendor/etc/fstab.qcom output/fstab.qcom
+            sudo umount vendor
+            sudo rm -rf vendor
 
-      - name: img_info && dtb Patching
+      - name: Mkbootimg
         run: |
-          echo "mkboot"
+          echo "mkbooting"
           mv output/boot.img mkbootimg/
           cd mkbootimg
           ./mkboot boot.img boot
           rm boot.img
           cd boot
-          sed -i 's/veritykeyid=id:\w*//g' img_info
-          cp img_info ../../output/
           cat img_info
-          cd ../../
-          mkdir tmp
-          mv mkbootimg/boot/kernel tmp/image.gz-dtb
-          mv flags.txt tmp/
-          cd tmp
-          ../split-appended-dtb image.gz-dtb
-          ls
-          rm image.gz-dtb
-          for i in `find *.dtb`; do
-              dts=${i%.*}.dts
-              dtc -q -I dtb -O dts -o $dts $i
-              rm -rf $i
-              if [ `grep -c "vbmeta" $dts` -ne '0' ];then
-                  echo $dts
-                  line="$(grep -n "firmware {" $dts)"
-                  linea="$(echo $line | cut -d ":" -f 1)"
-                  lineb="`expr $linea + 28`""p"
-                  sed -n "$linea,$lineb" $dts
-                  sed -i '/parts/{n;d;}' $dts
-                  sed -i '/vbmeta/d' $dts
-                  sed -i '/android,system/{n;d;}' $dts
-                  sed -i '/android,system/{n;d;}' $dts
-                  sed -i '/android,system/{n;d;}' $dts
-                  sed -i '/android,system/d' $dts
-                  sed -i '/,discard/{n;s/,slotselect//;}' *.dts
-                  sed -i 'N;/\n.*,slotselect/!P;D' $dts
-                  sed -i '/,slotselect/{n;d;}' $dts
-                  sed -i '/,slotselect/{n;d;}' $dts
-                  sed -i '/,slotselect/d' $dts
-                  sed -i '/,fstab/r flags.txt' $dts
-                  sed -i '/,fstab/G' $dts
-                  sed -i '/android,firmware/{n;d;}' $dts
-                  sed -i 's/,avb//g' $dts
-                  sed -i '/,slotselect/{n;s/disable/ok/;}' $dts
-                  sed -i 's/,slotselect//g' $dts
-                  line="$(grep -n "firmware {" $dts)"
-                  linea="$(echo $line | cut -d ":" -f 1)"
-                  lineb="`expr $linea + 24`""p"
-                  sed -n "$linea,$lineb" $dts
-              fi
-              cp $dts ../output/
-              dtc -q -I dts -O dtb -o $i $dts
-              rm -rf $dts
-          done
-          rm -f flags.txt
-          ls
-          cat kernel *.dtb > image.gz-dtb
-          rm -f *.dtb
-          rm -f kernel
-          ls
+          sed -i 's/androidboot.vbmeta.avb_version=...//g' img_info
+          cat img_info
+          cp img_info ../../output/
+          ls -al
           cd ..
-          mv tmp/image.gz-dtb mkbootimg/boot/kernel
-          rm -rf tmp
-          cd mkbootimg
           ./mkboot boot boot.img
+          ls -al
+          mv boot.img ../output/
           cd ..
+
+      - name: Mkdtimg
+        continue-on-error: true
+        run: |
+          echo "mkdting"
+          mv output/dtbo.img dtbo2dts/
+          cd dtbo2dts
+          python dtbo2dtsi.py
+          rm dtbo.img
+          ls -al
+          line="$(grep -n "vbmeta" dtsi.0)"
+          linea="$(echo $line | cut -d ":" -f 1)"
+          lineb="`expr $linea + 24`""p"
+          echo $linea
+          echo $lineb
+          sed -n "$linea,$lineb" dtsi.*
+          #sed -i '/parts/{n;d;}' dtsi.*
+          #sed -i '/parts/{n;d;}' dtsi.*
+          #sed -i '/vbmeta/d' dtsi.*
+          #sed -i '/android,vbmeta/d' dtsi.*
+          #sed -i '/parts/d' dtsi.*
+          sed -i 's/,slotselect//g' dtsi.*
+          sed -i 's/,avb//g' dtsi.*
+          sed -n "$linea,$lineb" dtsi.*
+          cp dtsi.* ../output/
+          python dtsi2dtbo.py
+          cp dtb_tmp.* ../output/
+          ls -al
+          cp dtbo_new.img ../output/dtbo.img
+          cd ../../
           
       - name: MakeMeSAR
         run: |
           mkdir tmp
-          mv mkbootimg/boot.img tmp/
+          mv output/boot.img tmp/
           cd tmp
           ../magiskboot unpack -h boot.img
-          cp ramdisk.cpio ../output/
-          sdk=$(sudo cat ../build.prop | grep ro.build.version.sdk | cut -d'=' -f2)
-          if [ "$sdk" -eq "31" ]; then
-              echo "sdk: "$sdk
-              cp -f ../12/ramdisk-sar.cpio ramdisk.cpio
-          else
-              echo "sdk -le 30"
-              cp -f ../ramdisk-sar.cpio ramdisk.cpio
-          fi
+          rm -f ramdisk.cpio
+          ls
           ../magiskboot repack boot.img
           ls -al
           cd ..
           mv tmp/new-boot.img output/boot.img
-          
+
+      - name: Patching vbmeta
+        run: |
+          echo "patching vbmeta"
+          ls output
+          ./magiskboot --help
+          xxd -c 256 -u output/vbmeta.img | grep "0000 0000 0000 0000 6176 6274" > /dev/null 2>&1
+          echo $?
+          if [ $? -eq 0 ]; then
+              echo "Hex match!!"
+              echo "Patching vbmeta..."
+              ./magiskboot hexpatch output/vbmeta.img 000000000000000061766274 000000020000000061766274
+              echo "Success!!!"
+          else
+              echo "TEST FAILED"
+              echo "Testing Another Method"
+              ./magiskboot hexpatch output/vbmeta.img 000000030000000061766274 000000020000000061766274
+          fi
+          od -w16 -An -tx1 output/vbmeta.img
+
       - name: Packing
         run: |
-          cp -f output/boot.img template/boot.img
+          mv output/boot.img template/boot.img
           mv output/system.img template/system.img
+          mv output/vendor.img template/vendor.img
+          mv output/dtbo.img template/dtbo.img
+          mv output/vbmeta.img template/vbmeta.img
           cd template
           ls -al
-          cd ..
           echo "--------------------------------------------"
-          mv template ${{ steps.var.outputs.filename }}
-          cd ${{ steps.var.outputs.filename }}
           zip -q -r -9 ${{ steps.var.outputs.filename }}.zip *
           cd ..
-          mv ${{ steps.var.outputs.filename }}/${{ steps.var.outputs.filename }}.zip ./
+          mv template/${{ steps.var.outputs.filename }}.zip ./
           ls -al
 
       - name: Upload to Artifact
@@ -194,6 +180,13 @@ jobs:
           path: |
             output
           retention-days: 7
+
+      - name: Upload to WeTransfer
+        run: |
+          curl -fsSL git.io/file-transfer | sh
+          wetrans=$(./transfer wet -s -p 16 --no-progress ${{ steps.var.outputs.filename }}.zip)
+          wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
+          echo "WeTransfer: $wetrans"
 
       - name: Upload to Release
         if: github.event.inputs.release == 'true'
